# Generated by Django 3.0 on 2019-12-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='联赛')),
                ('season', models.CharField(max_length=20, verbose_name='赛季')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '联赛',
                'verbose_name_plural': '联赛',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='国家')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='队伍')),
                ('abbr_name', models.CharField(max_length=20, verbose_name='缩写')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Nation', verbose_name='国家')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='赛程')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.League', verbose_name='联赛')),
            ],
            options={
                'verbose_name': '赛程',
                'verbose_name_plural': '赛程',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='主队得分')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='客队得分')),
                ('schedule_date', models.DateField(verbose_name='预计比赛日期')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='实际比赛日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='soccer.Team', verbose_name='客队')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='soccer.Team', verbose_name='主队')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='soccer.Schedule', verbose_name='轮次')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
            },
        ),
        migrations.AddField(
            model_name='league',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Nation', verbose_name='国家'),
        ),
    ]
